name: freezed_trainning
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  retrofit_generator: ^8.0.6
  test: ^1.24.0
